name: build docker image centos6

on: [ push, pull_request ]

jobs:
  build-docker-image-centos6:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        centos: ["centos6.6", "centos6.7", "centos6.8", "centos6.9", "centos6.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: "export docker image centos 6"
        shell: bash
        run: |
          docker pull centos:${{ matrix.centos }}
          docker save -o centos_${{ matrix.centos }}.tar centos:${{ matrix.centos }}
          mkdir ~/docker6
          mv centos_${{ matrix.centos }}.tar ~/docker6

      - uses: actions/upload-artifact@v2
        with:
          name: centos6
          path: |
            ~/docker6/*
          if-no-files-found: error
